#include <setsugen/math.h>

#define GENERATE_DEFINITION_FOR_MATRIX(type, col, row) \
    template class setsugen::Mat<type, col, row>;

#define GENERATE_DEFINITION_FOR_MATRIX_COL(type, col) \
    GENERATE_DEFINITION_FOR_MATRIX(type, col, 2) \
    GENERATE_DEFINITION_FOR_MATRIX(type, col, 3) \
    GENERATE_DEFINITION_FOR_MATRIX(type, col, 4)

#define GENERATE_DEFINITION_FOR_MATRIX_TYPE(type) \
    GENERATE_DEFINITION_FOR_MATRIX_COL(type, 2) \
    GENERATE_DEFINITION_FOR_MATRIX_COL(type, 3) \
    GENERATE_DEFINITION_FOR_MATRIX_COL(type, 4)

GENERATE_DEFINITION_FOR_MATRIX_TYPE(int)
GENERATE_DEFINITION_FOR_MATRIX_TYPE(unsigned int)
GENERATE_DEFINITION_FOR_MATRIX_TYPE(long long)
GENERATE_DEFINITION_FOR_MATRIX_TYPE(unsigned long long)
GENERATE_DEFINITION_FOR_MATRIX_TYPE(float)
GENERATE_DEFINITION_FOR_MATRIX_TYPE(double)

